// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common/plugin.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_common_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{0}
}

type MetadataResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Methods         []string               `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`                                                                                     // Available methods
	Capabilities    map[string]string      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional capabilities
	ProtocolVersion int32                  `protobuf:"varint,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`                                             // Protocol version the plugin was built with
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_common_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataResponse) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *MetadataResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *MetadataResponse) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                                                           // Method to execute
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Generic string parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_common_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *string                `protobuf:"bytes,1,opt,name=result,proto3,oneof" json:"result,omitempty"` // Result of the execution (present on success)
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`    // Whether the execution was successful
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`   // Optional error message if the execution was not successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_common_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_common_plugin_proto protoreflect.FileDescriptor

const file_common_plugin_proto_rawDesc = "" +
	"\n" +
	"\x13common/plugin.proto\x12\x06common\"\x11\n" +
	"\x0fMetadataRequest\"\xb8\x02\n" +
	"\x10MetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\amethods\x18\x04 \x03(\tR\amethods\x12N\n" +
	"\fcapabilities\x18\x05 \x03(\v2*.common.MetadataResponse.CapabilitiesEntryR\fcapabilities\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\x05R\x0fprotocolVersion\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12:\n" +
	"\x06params\x18\x02 \x03(\v2\".common.ExecuteRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x0fExecuteResponse\x12\x1b\n" +
	"\x06result\x18\x01 \x01(\tH\x00R\x06result\x88\x01\x01\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x01R\x05error\x88\x01\x01B\t\n" +
	"\a_resultB\b\n" +
	"\x06_error2\x86\x01\n" +
	"\x06Plugin\x12@\n" +
	"\vGetMetadata\x12\x17.common.MetadataRequest\x1a\x18.common.MetadataResponse\x12:\n" +
	"\aExecute\x12\x16.common.ExecuteRequest\x1a\x17.common.ExecuteResponseB\x8c\x01\n" +
	"\n" +
	"com.commonB\vPluginProtoP\x01Z9github.com/wylu1037/polyglot-plugin-showcase/proto/common\xa2\x02\x03CXX\xaa\x02\x06Common\xca\x02\x06Common\xe2\x02\x12Common\\GPBMetadata\xea\x02\x06Commonb\x06proto3"

var (
	file_common_plugin_proto_rawDescOnce sync.Once
	file_common_plugin_proto_rawDescData []byte
)

func file_common_plugin_proto_rawDescGZIP() []byte {
	file_common_plugin_proto_rawDescOnce.Do(func() {
		file_common_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_plugin_proto_rawDesc), len(file_common_plugin_proto_rawDesc)))
	})
	return file_common_plugin_proto_rawDescData
}

var file_common_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_plugin_proto_goTypes = []any{
	(*MetadataRequest)(nil),  // 0: common.MetadataRequest
	(*MetadataResponse)(nil), // 1: common.MetadataResponse
	(*ExecuteRequest)(nil),   // 2: common.ExecuteRequest
	(*ExecuteResponse)(nil),  // 3: common.ExecuteResponse
	nil,                      // 4: common.MetadataResponse.CapabilitiesEntry
	nil,                      // 5: common.ExecuteRequest.ParamsEntry
}
var file_common_plugin_proto_depIdxs = []int32{
	4, // 0: common.MetadataResponse.capabilities:type_name -> common.MetadataResponse.CapabilitiesEntry
	5, // 1: common.ExecuteRequest.params:type_name -> common.ExecuteRequest.ParamsEntry
	0, // 2: common.Plugin.GetMetadata:input_type -> common.MetadataRequest
	2, // 3: common.Plugin.Execute:input_type -> common.ExecuteRequest
	1, // 4: common.Plugin.GetMetadata:output_type -> common.MetadataResponse
	3, // 5: common.Plugin.Execute:output_type -> common.ExecuteResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_plugin_proto_init() }
func file_common_plugin_proto_init() {
	if File_common_plugin_proto != nil {
		return
	}
	file_common_plugin_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_plugin_proto_rawDesc), len(file_common_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_plugin_proto_goTypes,
		DependencyIndexes: file_common_plugin_proto_depIdxs,
		MessageInfos:      file_common_plugin_proto_msgTypes,
	}.Build()
	File_common_plugin_proto = out.File
	file_common_plugin_proto_goTypes = nil
	file_common_plugin_proto_depIdxs = nil
}
