// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: converter/converter.proto

package converter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                                                                 // JSON data to convert
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional conversion options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_converter_converter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_converter_converter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_converter_converter_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ConvertRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // Converted data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_converter_converter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_converter_converter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_converter_converter_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_converter_converter_proto protoreflect.FileDescriptor

const file_converter_converter_proto_rawDesc = "" +
	"\n" +
	"\x19converter/converter.proto\x12\tconverter\"\xa2\x01\n" +
	"\x0eConvertRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12@\n" +
	"\aoptions\x18\x02 \x03(\v2&.converter.ConvertRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x0fConvertResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xe1\x01\n" +
	"\tConverter\x12E\n" +
	"\fConvertToCSV\x12\x19.converter.ConvertRequest\x1a\x1a.converter.ConvertResponse\x12E\n" +
	"\fConvertToTXT\x12\x19.converter.ConvertRequest\x1a\x1a.converter.ConvertResponse\x12F\n" +
	"\rConvertToHTML\x12\x19.converter.ConvertRequest\x1a\x1a.converter.ConvertResponseB\xa1\x01\n" +
	"\rcom.converterB\x0eConverterProtoP\x01Z<github.com/wylu1037/polyglot-plugin-showcase/proto/converter\xa2\x02\x03CXX\xaa\x02\tConverter\xca\x02\tConverter\xe2\x02\x15Converter\\GPBMetadata\xea\x02\tConverterb\x06proto3"

var (
	file_converter_converter_proto_rawDescOnce sync.Once
	file_converter_converter_proto_rawDescData []byte
)

func file_converter_converter_proto_rawDescGZIP() []byte {
	file_converter_converter_proto_rawDescOnce.Do(func() {
		file_converter_converter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_converter_converter_proto_rawDesc), len(file_converter_converter_proto_rawDesc)))
	})
	return file_converter_converter_proto_rawDescData
}

var file_converter_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_converter_converter_proto_goTypes = []any{
	(*ConvertRequest)(nil),  // 0: converter.ConvertRequest
	(*ConvertResponse)(nil), // 1: converter.ConvertResponse
	nil,                     // 2: converter.ConvertRequest.OptionsEntry
}
var file_converter_converter_proto_depIdxs = []int32{
	2, // 0: converter.ConvertRequest.options:type_name -> converter.ConvertRequest.OptionsEntry
	0, // 1: converter.Converter.ConvertToCSV:input_type -> converter.ConvertRequest
	0, // 2: converter.Converter.ConvertToTXT:input_type -> converter.ConvertRequest
	0, // 3: converter.Converter.ConvertToHTML:input_type -> converter.ConvertRequest
	1, // 4: converter.Converter.ConvertToCSV:output_type -> converter.ConvertResponse
	1, // 5: converter.Converter.ConvertToTXT:output_type -> converter.ConvertResponse
	1, // 6: converter.Converter.ConvertToHTML:output_type -> converter.ConvertResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_converter_converter_proto_init() }
func file_converter_converter_proto_init() {
	if File_converter_converter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_converter_converter_proto_rawDesc), len(file_converter_converter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_converter_converter_proto_goTypes,
		DependencyIndexes: file_converter_converter_proto_depIdxs,
		MessageInfos:      file_converter_converter_proto_msgTypes,
	}.Build()
	File_converter_converter_proto = out.File
	file_converter_converter_proto_goTypes = nil
	file_converter_converter_proto_depIdxs = nil
}
