// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dpanonymizer/dpanonymizer.proto

package dpanonymizer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoiseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Epsilon       float64                `protobuf:"fixed64,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`         // Privacy budget
	Delta         float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`             // Failure probability (for Gaussian)
	Sensitivity   float64                `protobuf:"fixed64,4,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"` // Sensitivity of the query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseRequest) Reset() {
	*x = NoiseRequest{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseRequest) ProtoMessage() {}

func (x *NoiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseRequest.ProtoReflect.Descriptor instead.
func (*NoiseRequest) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{0}
}

func (x *NoiseRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NoiseRequest) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *NoiseRequest) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *NoiseRequest) GetSensitivity() float64 {
	if x != nil {
		return x.Sensitivity
	}
	return 0
}

type NoiseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseResponse) Reset() {
	*x = NoiseResponse{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseResponse) ProtoMessage() {}

func (x *NoiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseResponse.ProtoReflect.Descriptor instead.
func (*NoiseResponse) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{1}
}

func (x *NoiseResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type CountRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Values                   []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Epsilon                  float64                `protobuf:"fixed64,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Delta                    float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	MaxPartitionsContributed int64                  `protobuf:"varint,4,opt,name=max_partitions_contributed,json=maxPartitionsContributed,proto3" json:"max_partitions_contributed,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{2}
}

func (x *CountRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *CountRequest) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *CountRequest) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *CountRequest) GetMaxPartitionsContributed() int64 {
	if x != nil {
		return x.MaxPartitionsContributed
	}
	return 0
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{3}
}

func (x *CountResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SumRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Values                   []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Epsilon                  float64                `protobuf:"fixed64,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Delta                    float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	LowerBound               float64                `protobuf:"fixed64,4,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound               float64                `protobuf:"fixed64,5,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	MaxPartitionsContributed int64                  `protobuf:"varint,6,opt,name=max_partitions_contributed,json=maxPartitionsContributed,proto3" json:"max_partitions_contributed,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{4}
}

func (x *SumRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SumRequest) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *SumRequest) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *SumRequest) GetLowerBound() float64 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *SumRequest) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *SumRequest) GetMaxPartitionsContributed() int64 {
	if x != nil {
		return x.MaxPartitionsContributed
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{5}
}

func (x *SumResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MeanRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Values                   []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Epsilon                  float64                `protobuf:"fixed64,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Delta                    float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	LowerBound               float64                `protobuf:"fixed64,4,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound               float64                `protobuf:"fixed64,5,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	MaxPartitionsContributed int64                  `protobuf:"varint,6,opt,name=max_partitions_contributed,json=maxPartitionsContributed,proto3" json:"max_partitions_contributed,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MeanRequest) Reset() {
	*x = MeanRequest{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeanRequest) ProtoMessage() {}

func (x *MeanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeanRequest.ProtoReflect.Descriptor instead.
func (*MeanRequest) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{6}
}

func (x *MeanRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *MeanRequest) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *MeanRequest) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *MeanRequest) GetLowerBound() float64 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *MeanRequest) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *MeanRequest) GetMaxPartitionsContributed() int64 {
	if x != nil {
		return x.MaxPartitionsContributed
	}
	return 0
}

type MeanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeanResponse) Reset() {
	*x = MeanResponse{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeanResponse) ProtoMessage() {}

func (x *MeanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeanResponse.ProtoReflect.Descriptor instead.
func (*MeanResponse) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{7}
}

func (x *MeanResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type VarianceRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Values                   []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Epsilon                  float64                `protobuf:"fixed64,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Delta                    float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`
	LowerBound               float64                `protobuf:"fixed64,4,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound               float64                `protobuf:"fixed64,5,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	MaxPartitionsContributed int64                  `protobuf:"varint,6,opt,name=max_partitions_contributed,json=maxPartitionsContributed,proto3" json:"max_partitions_contributed,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *VarianceRequest) Reset() {
	*x = VarianceRequest{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VarianceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarianceRequest) ProtoMessage() {}

func (x *VarianceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarianceRequest.ProtoReflect.Descriptor instead.
func (*VarianceRequest) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{8}
}

func (x *VarianceRequest) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *VarianceRequest) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *VarianceRequest) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *VarianceRequest) GetLowerBound() float64 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *VarianceRequest) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *VarianceRequest) GetMaxPartitionsContributed() int64 {
	if x != nil {
		return x.MaxPartitionsContributed
	}
	return 0
}

type VarianceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VarianceResponse) Reset() {
	*x = VarianceResponse{}
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VarianceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarianceResponse) ProtoMessage() {}

func (x *VarianceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dpanonymizer_dpanonymizer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarianceResponse.ProtoReflect.Descriptor instead.
func (*VarianceResponse) Descriptor() ([]byte, []int) {
	return file_dpanonymizer_dpanonymizer_proto_rawDescGZIP(), []int{9}
}

func (x *VarianceResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_dpanonymizer_dpanonymizer_proto protoreflect.FileDescriptor

const file_dpanonymizer_dpanonymizer_proto_rawDesc = "" +
	"\n" +
	"\x1fdpanonymizer/dpanonymizer.proto\x12\fdpanonymizer\"v\n" +
	"\fNoiseRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x18\n" +
	"\aepsilon\x18\x02 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12 \n" +
	"\vsensitivity\x18\x04 \x01(\x01R\vsensitivity\"'\n" +
	"\rNoiseResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"\x94\x01\n" +
	"\fCountRequest\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12\x18\n" +
	"\aepsilon\x18\x02 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12<\n" +
	"\x1amax_partitions_contributed\x18\x04 \x01(\x03R\x18maxPartitionsContributed\"'\n" +
	"\rCountResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\"\xd4\x01\n" +
	"\n" +
	"SumRequest\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12\x18\n" +
	"\aepsilon\x18\x02 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12\x1f\n" +
	"\vlower_bound\x18\x04 \x01(\x01R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x05 \x01(\x01R\n" +
	"upperBound\x12<\n" +
	"\x1amax_partitions_contributed\x18\x06 \x01(\x03R\x18maxPartitionsContributed\"%\n" +
	"\vSumResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"\xd5\x01\n" +
	"\vMeanRequest\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12\x18\n" +
	"\aepsilon\x18\x02 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12\x1f\n" +
	"\vlower_bound\x18\x04 \x01(\x01R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x05 \x01(\x01R\n" +
	"upperBound\x12<\n" +
	"\x1amax_partitions_contributed\x18\x06 \x01(\x03R\x18maxPartitionsContributed\"&\n" +
	"\fMeanResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"\xd9\x01\n" +
	"\x0fVarianceRequest\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12\x18\n" +
	"\aepsilon\x18\x02 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12\x1f\n" +
	"\vlower_bound\x18\x04 \x01(\x01R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x05 \x01(\x01R\n" +
	"upperBound\x12<\n" +
	"\x1amax_partitions_contributed\x18\x06 \x01(\x03R\x18maxPartitionsContributed\"*\n" +
	"\x10VarianceResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result2\xb7\x03\n" +
	"\fDPAnonymizer\x12J\n" +
	"\x0fAddLaplaceNoise\x12\x1a.dpanonymizer.NoiseRequest\x1a\x1b.dpanonymizer.NoiseResponse\x12K\n" +
	"\x10AddGaussianNoise\x12\x1a.dpanonymizer.NoiseRequest\x1a\x1b.dpanonymizer.NoiseResponse\x12B\n" +
	"\aDPCount\x12\x1a.dpanonymizer.CountRequest\x1a\x1b.dpanonymizer.CountResponse\x12<\n" +
	"\x05DPSum\x12\x18.dpanonymizer.SumRequest\x1a\x19.dpanonymizer.SumResponse\x12?\n" +
	"\x06DPMean\x12\x19.dpanonymizer.MeanRequest\x1a\x1a.dpanonymizer.MeanResponse\x12K\n" +
	"\n" +
	"DPVariance\x12\x1d.dpanonymizer.VarianceRequest\x1a\x1e.dpanonymizer.VarianceResponseB\xb6\x01\n" +
	"\x10com.dpanonymizerB\x11DpanonymizerProtoP\x01Z?github.com/wylu1037/polyglot-plugin-showcase/proto/dpanonymizer\xa2\x02\x03DXX\xaa\x02\fDpanonymizer\xca\x02\fDpanonymizer\xe2\x02\x18Dpanonymizer\\GPBMetadata\xea\x02\fDpanonymizerb\x06proto3"

var (
	file_dpanonymizer_dpanonymizer_proto_rawDescOnce sync.Once
	file_dpanonymizer_dpanonymizer_proto_rawDescData []byte
)

func file_dpanonymizer_dpanonymizer_proto_rawDescGZIP() []byte {
	file_dpanonymizer_dpanonymizer_proto_rawDescOnce.Do(func() {
		file_dpanonymizer_dpanonymizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpanonymizer_dpanonymizer_proto_rawDesc), len(file_dpanonymizer_dpanonymizer_proto_rawDesc)))
	})
	return file_dpanonymizer_dpanonymizer_proto_rawDescData
}

var file_dpanonymizer_dpanonymizer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dpanonymizer_dpanonymizer_proto_goTypes = []any{
	(*NoiseRequest)(nil),     // 0: dpanonymizer.NoiseRequest
	(*NoiseResponse)(nil),    // 1: dpanonymizer.NoiseResponse
	(*CountRequest)(nil),     // 2: dpanonymizer.CountRequest
	(*CountResponse)(nil),    // 3: dpanonymizer.CountResponse
	(*SumRequest)(nil),       // 4: dpanonymizer.SumRequest
	(*SumResponse)(nil),      // 5: dpanonymizer.SumResponse
	(*MeanRequest)(nil),      // 6: dpanonymizer.MeanRequest
	(*MeanResponse)(nil),     // 7: dpanonymizer.MeanResponse
	(*VarianceRequest)(nil),  // 8: dpanonymizer.VarianceRequest
	(*VarianceResponse)(nil), // 9: dpanonymizer.VarianceResponse
}
var file_dpanonymizer_dpanonymizer_proto_depIdxs = []int32{
	0, // 0: dpanonymizer.DPAnonymizer.AddLaplaceNoise:input_type -> dpanonymizer.NoiseRequest
	0, // 1: dpanonymizer.DPAnonymizer.AddGaussianNoise:input_type -> dpanonymizer.NoiseRequest
	2, // 2: dpanonymizer.DPAnonymizer.DPCount:input_type -> dpanonymizer.CountRequest
	4, // 3: dpanonymizer.DPAnonymizer.DPSum:input_type -> dpanonymizer.SumRequest
	6, // 4: dpanonymizer.DPAnonymizer.DPMean:input_type -> dpanonymizer.MeanRequest
	8, // 5: dpanonymizer.DPAnonymizer.DPVariance:input_type -> dpanonymizer.VarianceRequest
	1, // 6: dpanonymizer.DPAnonymizer.AddLaplaceNoise:output_type -> dpanonymizer.NoiseResponse
	1, // 7: dpanonymizer.DPAnonymizer.AddGaussianNoise:output_type -> dpanonymizer.NoiseResponse
	3, // 8: dpanonymizer.DPAnonymizer.DPCount:output_type -> dpanonymizer.CountResponse
	5, // 9: dpanonymizer.DPAnonymizer.DPSum:output_type -> dpanonymizer.SumResponse
	7, // 10: dpanonymizer.DPAnonymizer.DPMean:output_type -> dpanonymizer.MeanResponse
	9, // 11: dpanonymizer.DPAnonymizer.DPVariance:output_type -> dpanonymizer.VarianceResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dpanonymizer_dpanonymizer_proto_init() }
func file_dpanonymizer_dpanonymizer_proto_init() {
	if File_dpanonymizer_dpanonymizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpanonymizer_dpanonymizer_proto_rawDesc), len(file_dpanonymizer_dpanonymizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dpanonymizer_dpanonymizer_proto_goTypes,
		DependencyIndexes: file_dpanonymizer_dpanonymizer_proto_depIdxs,
		MessageInfos:      file_dpanonymizer_dpanonymizer_proto_msgTypes,
	}.Build()
	File_dpanonymizer_dpanonymizer_proto = out.File
	file_dpanonymizer_dpanonymizer_proto_goTypes = nil
	file_dpanonymizer_dpanonymizer_proto_depIdxs = nil
}
