// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dpanonymizer/dpanonymizer.proto

package dpanonymizer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DPAnonymizer_AddLaplaceNoise_FullMethodName  = "/dpanonymizer.DPAnonymizer/AddLaplaceNoise"
	DPAnonymizer_AddGaussianNoise_FullMethodName = "/dpanonymizer.DPAnonymizer/AddGaussianNoise"
	DPAnonymizer_DPCount_FullMethodName          = "/dpanonymizer.DPAnonymizer/DPCount"
	DPAnonymizer_DPSum_FullMethodName            = "/dpanonymizer.DPAnonymizer/DPSum"
	DPAnonymizer_DPMean_FullMethodName           = "/dpanonymizer.DPAnonymizer/DPMean"
	DPAnonymizer_DPVariance_FullMethodName       = "/dpanonymizer.DPAnonymizer/DPVariance"
)

// DPAnonymizerClient is the client API for DPAnonymizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DPAnonymizer service definition for differential privacy based anonymization
type DPAnonymizerClient interface {
	// Add Laplace noise to a numeric value
	AddLaplaceNoise(ctx context.Context, in *NoiseRequest, opts ...grpc.CallOption) (*NoiseResponse, error)
	// Add Gaussian noise to a numeric value
	AddGaussianNoise(ctx context.Context, in *NoiseRequest, opts ...grpc.CallOption) (*NoiseResponse, error)
	// Calculate differentially private count
	DPCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// Calculate differentially private sum
	DPSum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	// Calculate differentially private mean
	DPMean(ctx context.Context, in *MeanRequest, opts ...grpc.CallOption) (*MeanResponse, error)
	// Calculate differentially private variance
	DPVariance(ctx context.Context, in *VarianceRequest, opts ...grpc.CallOption) (*VarianceResponse, error)
}

type dPAnonymizerClient struct {
	cc grpc.ClientConnInterface
}

func NewDPAnonymizerClient(cc grpc.ClientConnInterface) DPAnonymizerClient {
	return &dPAnonymizerClient{cc}
}

func (c *dPAnonymizerClient) AddLaplaceNoise(ctx context.Context, in *NoiseRequest, opts ...grpc.CallOption) (*NoiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoiseResponse)
	err := c.cc.Invoke(ctx, DPAnonymizer_AddLaplaceNoise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPAnonymizerClient) AddGaussianNoise(ctx context.Context, in *NoiseRequest, opts ...grpc.CallOption) (*NoiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoiseResponse)
	err := c.cc.Invoke(ctx, DPAnonymizer_AddGaussianNoise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPAnonymizerClient) DPCount(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, DPAnonymizer_DPCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPAnonymizerClient) DPSum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, DPAnonymizer_DPSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPAnonymizerClient) DPMean(ctx context.Context, in *MeanRequest, opts ...grpc.CallOption) (*MeanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeanResponse)
	err := c.cc.Invoke(ctx, DPAnonymizer_DPMean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dPAnonymizerClient) DPVariance(ctx context.Context, in *VarianceRequest, opts ...grpc.CallOption) (*VarianceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VarianceResponse)
	err := c.cc.Invoke(ctx, DPAnonymizer_DPVariance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DPAnonymizerServer is the server API for DPAnonymizer service.
// All implementations must embed UnimplementedDPAnonymizerServer
// for forward compatibility.
//
// DPAnonymizer service definition for differential privacy based anonymization
type DPAnonymizerServer interface {
	// Add Laplace noise to a numeric value
	AddLaplaceNoise(context.Context, *NoiseRequest) (*NoiseResponse, error)
	// Add Gaussian noise to a numeric value
	AddGaussianNoise(context.Context, *NoiseRequest) (*NoiseResponse, error)
	// Calculate differentially private count
	DPCount(context.Context, *CountRequest) (*CountResponse, error)
	// Calculate differentially private sum
	DPSum(context.Context, *SumRequest) (*SumResponse, error)
	// Calculate differentially private mean
	DPMean(context.Context, *MeanRequest) (*MeanResponse, error)
	// Calculate differentially private variance
	DPVariance(context.Context, *VarianceRequest) (*VarianceResponse, error)
	mustEmbedUnimplementedDPAnonymizerServer()
}

// UnimplementedDPAnonymizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDPAnonymizerServer struct{}

func (UnimplementedDPAnonymizerServer) AddLaplaceNoise(context.Context, *NoiseRequest) (*NoiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLaplaceNoise not implemented")
}
func (UnimplementedDPAnonymizerServer) AddGaussianNoise(context.Context, *NoiseRequest) (*NoiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGaussianNoise not implemented")
}
func (UnimplementedDPAnonymizerServer) DPCount(context.Context, *CountRequest) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPCount not implemented")
}
func (UnimplementedDPAnonymizerServer) DPSum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPSum not implemented")
}
func (UnimplementedDPAnonymizerServer) DPMean(context.Context, *MeanRequest) (*MeanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPMean not implemented")
}
func (UnimplementedDPAnonymizerServer) DPVariance(context.Context, *VarianceRequest) (*VarianceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DPVariance not implemented")
}
func (UnimplementedDPAnonymizerServer) mustEmbedUnimplementedDPAnonymizerServer() {}
func (UnimplementedDPAnonymizerServer) testEmbeddedByValue()                      {}

// UnsafeDPAnonymizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DPAnonymizerServer will
// result in compilation errors.
type UnsafeDPAnonymizerServer interface {
	mustEmbedUnimplementedDPAnonymizerServer()
}

func RegisterDPAnonymizerServer(s grpc.ServiceRegistrar, srv DPAnonymizerServer) {
	// If the following call pancis, it indicates UnimplementedDPAnonymizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DPAnonymizer_ServiceDesc, srv)
}

func _DPAnonymizer_AddLaplaceNoise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPAnonymizerServer).AddLaplaceNoise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPAnonymizer_AddLaplaceNoise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPAnonymizerServer).AddLaplaceNoise(ctx, req.(*NoiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPAnonymizer_AddGaussianNoise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPAnonymizerServer).AddGaussianNoise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPAnonymizer_AddGaussianNoise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPAnonymizerServer).AddGaussianNoise(ctx, req.(*NoiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPAnonymizer_DPCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPAnonymizerServer).DPCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPAnonymizer_DPCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPAnonymizerServer).DPCount(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPAnonymizer_DPSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPAnonymizerServer).DPSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPAnonymizer_DPSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPAnonymizerServer).DPSum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPAnonymizer_DPMean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPAnonymizerServer).DPMean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPAnonymizer_DPMean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPAnonymizerServer).DPMean(ctx, req.(*MeanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DPAnonymizer_DPVariance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VarianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DPAnonymizerServer).DPVariance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DPAnonymizer_DPVariance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DPAnonymizerServer).DPVariance(ctx, req.(*VarianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DPAnonymizer_ServiceDesc is the grpc.ServiceDesc for DPAnonymizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DPAnonymizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dpanonymizer.DPAnonymizer",
	HandlerType: (*DPAnonymizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLaplaceNoise",
			Handler:    _DPAnonymizer_AddLaplaceNoise_Handler,
		},
		{
			MethodName: "AddGaussianNoise",
			Handler:    _DPAnonymizer_AddGaussianNoise_Handler,
		},
		{
			MethodName: "DPCount",
			Handler:    _DPAnonymizer_DPCount_Handler,
		},
		{
			MethodName: "DPSum",
			Handler:    _DPAnonymizer_DPSum_Handler,
		},
		{
			MethodName: "DPMean",
			Handler:    _DPAnonymizer_DPMean_Handler,
		},
		{
			MethodName: "DPVariance",
			Handler:    _DPAnonymizer_DPVariance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dpanonymizer/dpanonymizer.proto",
}
