// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: desensitization/desensitizer.proto

package desensitization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DesensitizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesensitizeRequest) Reset() {
	*x = DesensitizeRequest{}
	mi := &file_desensitization_desensitizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesensitizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesensitizeRequest) ProtoMessage() {}

func (x *DesensitizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desensitization_desensitizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesensitizeRequest.ProtoReflect.Descriptor instead.
func (*DesensitizeRequest) Descriptor() ([]byte, []int) {
	return file_desensitization_desensitizer_proto_rawDescGZIP(), []int{0}
}

func (x *DesensitizeRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DesensitizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesensitizeResponse) Reset() {
	*x = DesensitizeResponse{}
	mi := &file_desensitization_desensitizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesensitizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesensitizeResponse) ProtoMessage() {}

func (x *DesensitizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desensitization_desensitizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesensitizeResponse.ProtoReflect.Descriptor instead.
func (*DesensitizeResponse) Descriptor() ([]byte, []int) {
	return file_desensitization_desensitizer_proto_rawDescGZIP(), []int{1}
}

func (x *DesensitizeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_desensitization_desensitizer_proto protoreflect.FileDescriptor

const file_desensitization_desensitizer_proto_rawDesc = "" +
	"\n" +
	"\"desensitization/desensitizer.proto\x12\x0fdesensitization\"(\n" +
	"\x12DesensitizeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"-\n" +
	"\x13DesensitizeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2\xcf\x04\n" +
	"\fDesensitizer\x12\\\n" +
	"\x0fDesensitizeName\x12#.desensitization.DesensitizeRequest\x1a$.desensitization.DesensitizeResponse\x12]\n" +
	"\x10DesensitizeTelNo\x12#.desensitization.DesensitizeRequest\x1a$.desensitization.DesensitizeResponse\x12`\n" +
	"\x13DesensitizeIDNumber\x12#.desensitization.DesensitizeRequest\x1a$.desensitization.DesensitizeResponse\x12]\n" +
	"\x10DesensitizeEmail\x12#.desensitization.DesensitizeRequest\x1a$.desensitization.DesensitizeResponse\x12`\n" +
	"\x13DesensitizeBankCard\x12#.desensitization.DesensitizeRequest\x1a$.desensitization.DesensitizeResponse\x12_\n" +
	"\x12DesensitizeAddress\x12#.desensitization.DesensitizeRequest\x1a$.desensitization.DesensitizeResponseB\xc8\x01\n" +
	"\x13com.desensitizationB\x11DesensitizerProtoP\x01ZBgithub.com/wylu1037/polyglot-plugin-showcase/proto/desensitization\xa2\x02\x03DXX\xaa\x02\x0fDesensitization\xca\x02\x0fDesensitization\xe2\x02\x1bDesensitization\\GPBMetadata\xea\x02\x0fDesensitizationb\x06proto3"

var (
	file_desensitization_desensitizer_proto_rawDescOnce sync.Once
	file_desensitization_desensitizer_proto_rawDescData []byte
)

func file_desensitization_desensitizer_proto_rawDescGZIP() []byte {
	file_desensitization_desensitizer_proto_rawDescOnce.Do(func() {
		file_desensitization_desensitizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desensitization_desensitizer_proto_rawDesc), len(file_desensitization_desensitizer_proto_rawDesc)))
	})
	return file_desensitization_desensitizer_proto_rawDescData
}

var file_desensitization_desensitizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_desensitization_desensitizer_proto_goTypes = []any{
	(*DesensitizeRequest)(nil),  // 0: desensitization.DesensitizeRequest
	(*DesensitizeResponse)(nil), // 1: desensitization.DesensitizeResponse
}
var file_desensitization_desensitizer_proto_depIdxs = []int32{
	0, // 0: desensitization.Desensitizer.DesensitizeName:input_type -> desensitization.DesensitizeRequest
	0, // 1: desensitization.Desensitizer.DesensitizeTelNo:input_type -> desensitization.DesensitizeRequest
	0, // 2: desensitization.Desensitizer.DesensitizeIDNumber:input_type -> desensitization.DesensitizeRequest
	0, // 3: desensitization.Desensitizer.DesensitizeEmail:input_type -> desensitization.DesensitizeRequest
	0, // 4: desensitization.Desensitizer.DesensitizeBankCard:input_type -> desensitization.DesensitizeRequest
	0, // 5: desensitization.Desensitizer.DesensitizeAddress:input_type -> desensitization.DesensitizeRequest
	1, // 6: desensitization.Desensitizer.DesensitizeName:output_type -> desensitization.DesensitizeResponse
	1, // 7: desensitization.Desensitizer.DesensitizeTelNo:output_type -> desensitization.DesensitizeResponse
	1, // 8: desensitization.Desensitizer.DesensitizeIDNumber:output_type -> desensitization.DesensitizeResponse
	1, // 9: desensitization.Desensitizer.DesensitizeEmail:output_type -> desensitization.DesensitizeResponse
	1, // 10: desensitization.Desensitizer.DesensitizeBankCard:output_type -> desensitization.DesensitizeResponse
	1, // 11: desensitization.Desensitizer.DesensitizeAddress:output_type -> desensitization.DesensitizeResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_desensitization_desensitizer_proto_init() }
func file_desensitization_desensitizer_proto_init() {
	if File_desensitization_desensitizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desensitization_desensitizer_proto_rawDesc), len(file_desensitization_desensitizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desensitization_desensitizer_proto_goTypes,
		DependencyIndexes: file_desensitization_desensitizer_proto_depIdxs,
		MessageInfos:      file_desensitization_desensitizer_proto_msgTypes,
	}.Build()
	File_desensitization_desensitizer_proto = out.File
	file_desensitization_desensitizer_proto_goTypes = nil
	file_desensitization_desensitizer_proto_depIdxs = nil
}
