// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: desensitization/desensitizer.proto

package desensitization

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Desensitizer_DesensitizeName_FullMethodName     = "/desensitization.Desensitizer/DesensitizeName"
	Desensitizer_DesensitizeTelNo_FullMethodName    = "/desensitization.Desensitizer/DesensitizeTelNo"
	Desensitizer_DesensitizeIDNumber_FullMethodName = "/desensitization.Desensitizer/DesensitizeIDNumber"
	Desensitizer_DesensitizeEmail_FullMethodName    = "/desensitization.Desensitizer/DesensitizeEmail"
	Desensitizer_DesensitizeBankCard_FullMethodName = "/desensitization.Desensitizer/DesensitizeBankCard"
	Desensitizer_DesensitizeAddress_FullMethodName  = "/desensitization.Desensitizer/DesensitizeAddress"
)

// DesensitizerClient is the client API for Desensitizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Desensitizer service definition
type DesensitizerClient interface {
	DesensitizeName(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error)
	DesensitizeTelNo(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error)
	DesensitizeIDNumber(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error)
	DesensitizeEmail(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error)
	DesensitizeBankCard(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error)
	DesensitizeAddress(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error)
}

type desensitizerClient struct {
	cc grpc.ClientConnInterface
}

func NewDesensitizerClient(cc grpc.ClientConnInterface) DesensitizerClient {
	return &desensitizerClient{cc}
}

func (c *desensitizerClient) DesensitizeName(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesensitizeResponse)
	err := c.cc.Invoke(ctx, Desensitizer_DesensitizeName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desensitizerClient) DesensitizeTelNo(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesensitizeResponse)
	err := c.cc.Invoke(ctx, Desensitizer_DesensitizeTelNo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desensitizerClient) DesensitizeIDNumber(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesensitizeResponse)
	err := c.cc.Invoke(ctx, Desensitizer_DesensitizeIDNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desensitizerClient) DesensitizeEmail(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesensitizeResponse)
	err := c.cc.Invoke(ctx, Desensitizer_DesensitizeEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desensitizerClient) DesensitizeBankCard(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesensitizeResponse)
	err := c.cc.Invoke(ctx, Desensitizer_DesensitizeBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desensitizerClient) DesensitizeAddress(ctx context.Context, in *DesensitizeRequest, opts ...grpc.CallOption) (*DesensitizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesensitizeResponse)
	err := c.cc.Invoke(ctx, Desensitizer_DesensitizeAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesensitizerServer is the server API for Desensitizer service.
// All implementations must embed UnimplementedDesensitizerServer
// for forward compatibility.
//
// Desensitizer service definition
type DesensitizerServer interface {
	DesensitizeName(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error)
	DesensitizeTelNo(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error)
	DesensitizeIDNumber(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error)
	DesensitizeEmail(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error)
	DesensitizeBankCard(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error)
	DesensitizeAddress(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error)
	mustEmbedUnimplementedDesensitizerServer()
}

// UnimplementedDesensitizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesensitizerServer struct{}

func (UnimplementedDesensitizerServer) DesensitizeName(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesensitizeName not implemented")
}
func (UnimplementedDesensitizerServer) DesensitizeTelNo(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesensitizeTelNo not implemented")
}
func (UnimplementedDesensitizerServer) DesensitizeIDNumber(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesensitizeIDNumber not implemented")
}
func (UnimplementedDesensitizerServer) DesensitizeEmail(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesensitizeEmail not implemented")
}
func (UnimplementedDesensitizerServer) DesensitizeBankCard(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesensitizeBankCard not implemented")
}
func (UnimplementedDesensitizerServer) DesensitizeAddress(context.Context, *DesensitizeRequest) (*DesensitizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesensitizeAddress not implemented")
}
func (UnimplementedDesensitizerServer) mustEmbedUnimplementedDesensitizerServer() {}
func (UnimplementedDesensitizerServer) testEmbeddedByValue()                      {}

// UnsafeDesensitizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesensitizerServer will
// result in compilation errors.
type UnsafeDesensitizerServer interface {
	mustEmbedUnimplementedDesensitizerServer()
}

func RegisterDesensitizerServer(s grpc.ServiceRegistrar, srv DesensitizerServer) {
	// If the following call pancis, it indicates UnimplementedDesensitizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Desensitizer_ServiceDesc, srv)
}

func _Desensitizer_DesensitizeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesensitizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesensitizerServer).DesensitizeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Desensitizer_DesensitizeName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesensitizerServer).DesensitizeName(ctx, req.(*DesensitizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Desensitizer_DesensitizeTelNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesensitizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesensitizerServer).DesensitizeTelNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Desensitizer_DesensitizeTelNo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesensitizerServer).DesensitizeTelNo(ctx, req.(*DesensitizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Desensitizer_DesensitizeIDNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesensitizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesensitizerServer).DesensitizeIDNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Desensitizer_DesensitizeIDNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesensitizerServer).DesensitizeIDNumber(ctx, req.(*DesensitizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Desensitizer_DesensitizeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesensitizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesensitizerServer).DesensitizeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Desensitizer_DesensitizeEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesensitizerServer).DesensitizeEmail(ctx, req.(*DesensitizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Desensitizer_DesensitizeBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesensitizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesensitizerServer).DesensitizeBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Desensitizer_DesensitizeBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesensitizerServer).DesensitizeBankCard(ctx, req.(*DesensitizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Desensitizer_DesensitizeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesensitizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesensitizerServer).DesensitizeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Desensitizer_DesensitizeAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesensitizerServer).DesensitizeAddress(ctx, req.(*DesensitizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Desensitizer_ServiceDesc is the grpc.ServiceDesc for Desensitizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Desensitizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "desensitization.Desensitizer",
	HandlerType: (*DesensitizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DesensitizeName",
			Handler:    _Desensitizer_DesensitizeName_Handler,
		},
		{
			MethodName: "DesensitizeTelNo",
			Handler:    _Desensitizer_DesensitizeTelNo_Handler,
		},
		{
			MethodName: "DesensitizeIDNumber",
			Handler:    _Desensitizer_DesensitizeIDNumber_Handler,
		},
		{
			MethodName: "DesensitizeEmail",
			Handler:    _Desensitizer_DesensitizeEmail_Handler,
		},
		{
			MethodName: "DesensitizeBankCard",
			Handler:    _Desensitizer_DesensitizeBankCard_Handler,
		},
		{
			MethodName: "DesensitizeAddress",
			Handler:    _Desensitizer_DesensitizeAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desensitization/desensitizer.proto",
}
